FROM microsoft/dotnet:2.1-sdk AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.1-runtime-stretch-slim-arm32v7
RUN apt-get update && apt-get install -y mplayer
WORKDIR /app
COPY --from=build-env /app/out ./

RUN useradd -ms /bin/bash moduleuser
RUN adduser moduleuser audio
USER moduleuser

ENTRYPOINT ["dotnet", "PlayMessage.dll"]